name: Rust CI
on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      # Use cachix for faster builds (optional)
      - uses: cachix/cachix-action@v15
        if: ${{ secrets.CACHIX_AUTH_TOKEN }}
        with:
          name: jasper-companion
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      
      # Enter dev shell and run tests
      - name: Run tests
        run: nix develop --command cargo test --all-features
        
      - name: Run clippy
        run: nix develop --command cargo clippy -- -D warnings
        
      - name: Check formatting
        run: nix develop --command cargo fmt --check
        
      # Build for release to ensure it works
      - name: Build release
        run: nix develop --command cargo build --release